services:
  - type: web
    name: ball-mongrel
    runtime: node
    plan: free
    buildCommand: npm ci && npm run build
    startCommand: npm run start
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: ball-mongrel-db
          property: connectionString

databases:
  - name: ball-mongrel-db
    plan: free

